name: Build Fluent Bit Plugins on Push

on:
  push:
    branches:
      - "*"  # Trigger on push to any branch

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Build the plugin using Docker
    - name: Build Fluent Bit Plugins
      run: |
        echo "Building Fluent Bit plugins..."
        docker build -t lm-logs-fluentbit .
        docker run --rm -v $PWD:/build lm-logs-fluentbit \
          cp -r /go/src/lm/build /build/

    # Step 3: Upload generated .so files as artifacts
    - name: Upload .so files
      uses: actions/upload-artifact@v3
      with:
        name: fluent-bit-plugins
        path: plugins/*.so

    # Optional Step 4: Commit the .so files back to the repository
    - name: Commit and Push Generated .so Files
      if: github.ref != 'refs/heads/main' # Optionally skip committing to the main branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Committing generated .so files..."
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add plugins/*.so
        git commit -m "Update: Generated .so files on ${{ github.ref_name }}"
        git push
