name: Build Fluent Bit Plugins on Push

on:
  push:
    branches:
      - windows-plugin-generation

jobs:
  build-and-update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Plugin Depending on OS
      - name: Build Fluent Bit Plugins (.so or .dll)
        run: |
          echo "Running on ${{ runner.os }}"
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            echo "Building .so plugin..."
            docker build -t lm-logs-fluentbit .
            docker run --rm -v $PWD:/build lm-logs-fluentbit \
              bash -c "mkdir -p /build/plugins && cp -r /go/src/lm/build/*.so /build/plugins/"
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "Building .dll plugin..."
            mkdir -p plugins
            go build -buildmode=c-shared -o plugins/out_lm-windows.dll out_lm.go
          fi
        shell: bash

      # Step 3: List Files
      - name: Debug List workspace files
        run: |
          echo "Workspace file structure:"
          ls -R
        shell: bash

      # Step 4: Upload both .so and .dll if they exist
      - name: Upload Plugin Artifacts (.so / .dll)
        uses: actions/upload-artifact@v4
        with:
          name: fluent-bit-plugins-${{ matrix.os }}
          path: |
            plugins/**/*.so
            plugins/**/*.dll

      # Step 5: Commit .so/.dll if present
      - name: Commit and Push Generated Plugin Files
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking for plugin files to commit..."
          FILES=$(find plugins -type f \( -name '*.so' -o -name '*.dll' \))
          
          if [ -n "$FILES" ]; then
            git config user.name "GitHub Actions Bot"
            git config user.email "actions@github.com"
            git stash
          
            git pull --rebase origin ${{ github.ref_name }}
            git stash pop || true
          
            git add -f $FILES
            git commit -m "Update: Generated plugin files (.so/.dll) on ${{ github.ref_name }}"
            git push
          else
            echo "No plugin files to commit."
          fi
        shell: bash
